spring:
  application:
    name: cobranca-config-serve
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
cobranca-config-serve:
   greeting: "hello"
   default-value: "Word"
