spring:
  application:
    name: cobranca-config-serve
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
cobranca-config-serve:
   greeting: "Olá"
   default-value: "Mundo"
